export const TASK_TYPE_REQUEST = "TASK_TYPE_REQUEST";
export const TASK_TYPE_SUCCESS = "TASK_TYPE_SUCCESS";
export const TASK_TYPE_FAIL = "TASK_TYPE_FAIL";

export const PRIORITY_REQUEST = "PRIORITY_REQUEST";
export const PRIORITY_SUCCESS = "PRIORITY_SUCCESS";
export const PRIORITY_FAIL = "PRIORITY_FAIL";

export const STATUS_REQUEST = "STATUS_REQUEST";
export const STATUS_SUCCESS = "STATUS_SUCCESS";
export const STATUS_FAIL = "STATUS_FAIL";

export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_SUCCESS = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL = "CREATE_TASK_FAIL";
export const INFO_TASK = "INFO_TASK";


export const USER_BY_PROJECT_REQUEST = "USER_BY_PROJECT_REQUEST";
export const USER_BY_PROJECT_SUCCESS = "USER_BY_PROJECT_SUCCESS";
export const USER_BY_PROJECT_FAIL = "USER_BY_PROJECT_FAIL";