export const BOARD_REQUEST = "BOARD_REQUEST";
export const BOARD_SUCCESS = "BOARD_SUCCESS";
export const BOARD_FAIL = "BOARD_FAIL";


export const TASK_DETAIL_REQUEST = "TASK_DETAIL_REQUEST";
export const TASK_DETAIL_SUCCESS = "TASK_DETAIL_SUCCESS";
export const TASK_DETAIL_FAIL = "TASK_DETAIL_FAIL";
export const INFO_TASK_DETAIL = "INFO_TASK_DETAIL";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL";