export const PROJECT_CATEGORY_REQUEST = "PROJECT_CATEGORY_REQUEST";
export const PROJECT_CATEGORY_SUCCESS = "PROJECT_CATEGORY_SUCCESS";
export const PROJECT_CATEGORY_FAIL = "PROJECT_CATEGORY_FAIL";


export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";

