export const PROFILE_USER_REQUEST = "PROFILE_USER_REQUEST";
export const PROFILE_USER_SUCCESS = "PROFILE_USER_SUCCESS";
export const PROFILE_USER_FAIL = "PROFILE_USER_FAIL";


export const PROFILE_USER = "PROFILE_USER";


export const UPDATE_PROFILE_USER_REQUEST = "UPDATE_PROFILE_USER_REQUEST";
export const UPDATE_PROFILE_USER_SUCCESS = "UPDATE_PROFILE_USER_SUCCESS";
export const UPDATE_PROFILE_USER_FAIL = "UPDATE_PROFILE_USER_FAIL";
